# Generated by Django 3.0.8 on 2021-11-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=45)),
                ('amount', models.CharField(max_length=45)),
                ('expense_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('revenue', models.CharField(max_length=45)),
                ('credit_date', models.DateField()),
                ('revenue_type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'revenue',
                'managed': False,
            },
        ),
    ]
